/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-12-01 00:19:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<nav class=\"navbar navbar-default\">\n");
      out.write(" <div class=\"container-fluid\">\n");
      out.write(" <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write(" <div class=\"navbar-header\">\n");
      out.write(" <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\n");
      out.write(" <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write(" <span class=\"icon-bar\"></span>\n");
      out.write(" <span class=\"icon-bar\"></span>\n");
      out.write(" <span class=\"icon-bar\"></span>\n");
      out.write(" </button>\n");
      out.write(" <img src=\"images/bullhornlogo50x50.png\" alt=\"Bullhorn Logo\"/>&nbsp;<h2>Bullhorn</h2>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write(" <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write(" \n");
      out.write(" <ul class=\"nav navbar-nav\">\n");
      out.write(" <li class=\"active\"><a href=\"home.jsp\">Home<span class=\"sr-only\">(current)</span></a></li>\n");
      out.write(" <li><a href=\"Newsfeed\">News Feed</a></li> \n");
      out.write(" </ul>\n");
      out.write(" \n");
      out.write(" <form class=\"navbar-form navbar-right\" role=\"search\" action=\"Newsfeed\" method=\"get\">\n");
      out.write(" <div class=\"form-group\">\n");
      out.write(" <input type=\"text\" class=\"form-control\" placeholder=\"Search\" name=\"searchtext\">\n");
      out.write(" </div>\n");
      out.write(" <button type=\"submit\" class=\"btn btn-default\">Submit</button>\n");
      out.write(" </form>\n");
      out.write(" \n");
      out.write(" <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write(" ");
 if (session.getAttribute("user") != null) { 
      out.write("\n");
      out.write(" <li><a href=\"ProfileServlet?userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.bhuserid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&action=viewprofile\"><img alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gravatarURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></li>\n");
      out.write(" ");
 } 
      out.write("\n");
      out.write(" <li class=\"dropdown\">\n");
      out.write(" <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">User Options <span class=\"caret\"></span></a>\n");
      out.write(" <ul class=\"dropdown-menu\">\n");
      out.write(" <li>\n");
      out.write(" <!-- <li><a href=\"LoginServlet?action=logout\">Logout</a></li>-->\n");
      out.write(" <!-- Bootstrap allows me to put a form here and it will show in the navbar.\n");
      out.write(" I want to use a form so it can call the servlet with the Post method. \n");
      out.write(" -->\n");
      out.write(" <form class=\"navbar-form navbar-left\" role=\"form\" action=\"LoginServlet\" method=\"post\">\n");
      out.write(" <input type=\"hidden\" name=\"action\" id=\"action\" value=\"logout\"/>\n");
      out.write(" <button class=\"btn btn-default\" id=\"addBookButton\">Logout</button> \n");
      out.write(" </form>\n");
      out.write(" </li>\n");
      out.write(" <li><a href=\"Newsfeed?userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.bhuserid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Show my Posts</a></li>\n");
      out.write(" <li><a href=\"ProfileServlet?userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.bhuserid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&action=editprofile\">Edit Profile</a></li>\n");
      out.write(" <li role=\"separator\" class=\"divider\"></li>\n");
      out.write(" <li><a href=\"support.jsp\">Feedback</a></li>\n");
      out.write(" </ul>\n");
      out.write(" </li>\n");
      out.write(" </ul>\n");
      out.write(" </div><!-- /.navbar-collapse -->\n");
      out.write(" </div><!-- /.container-fluid -->\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
